# Generated by Django 3.2.7 on 2021-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211111_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
