# Generated by Django 3.2.7 on 2021-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_review_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(null=True, to='main.Genres'),
        ),
    ]
