# Generated by Django 3.2.7 on 2021-11-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
