# Generated by Django 3.2.7 on 2021-12-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='surname',
        ),
    ]
