# Generated by Django 3.2.7 on 2021-12-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211202_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
